version: '3.4'

services:
  web:
    build: .
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DbContext=Host=db;Database=postgres;Username=postgres;Password=postgres
  
  db:
    image: postgres:latest
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
